// Copyright (c) 2004-2020 Microchip Technology Inc. and its subsidiaries.
// SPDX-License-Identifier: MIT

= Getting started

== Getting started

The easiest and best way to get started with the MEPA library is to start using
it.

== Pre-requests and preparations

In order to follow this getting started guide, a version of the MEPA package
and a PHY is needed.

To build and load the MEPA library a Linux development machine with root access
is needed. This guide is using a Ubuntu Server version 18.04.

=== Installing basic SW dependencies

The first step is to install a couple of host tools needed by MEPA. The package
manager and the name of the specific packages differ from one Linux distribution
to another. Here are the instructions on how to do this on Ubuntu 18:

----
sudo apt-get install cmake cmake-curses-gui build-essential ruby ruby-parslet libjson-c-dev
----

Beside from this, the folder `/opt/mscc` must be created, and the user(s) building MEPA, but have the needed credentials to access this folder.
This folder is used to store dependent projects such as the BSP and toolchain.

The user which will download and install these dependent proejcts in `/opt/mscc` must have write access to this folder.

The user installing and the user building may be the same or different user/group.

Next we need a folder called `mscc` in `/opt` where the toolchains
and BSP will be installed as explained later in the guide.

----
sudo mkdir -p /opt/mscc
----

== Extracting the sources

The first step is to extract the MEPA package:

----
$ tar xf mepa-<version>.tar.gz
$ cd mepa-<version>
----

Note: MEPA related source is present in mepa-<version>/mepa.

== Create a CMake project (and download BSP and toolchain)

To build the sources a CMake project is needed. The easiest way to create a
CMake project is to use the `./.cmake/create_cmake_project.rb` script:

----
$ ./.cmake/create_cmake_project.rb
Usage: create_cmake_project <preset name> [output-folder]

Valid presets:
    mipsel
    mipsel-debug
    arm64
    arm64-debug
    arm64-asan
    arm
    arm-debug
    x86
----

Lets prepare a project for arm64 based targets:

----

./.cmake/create_cmake_project.rb arm64
----

Once the script is run the appropriate released package will be extracted in /opt/mscc/ folder.
The BSP source package will be also be installed automatically if not availbale in /opt/mscc/.

----
{MESA}: mesa-v2025.09
Fetching latest copy...
{BSP}: mscc-brsdk-arm64-2024.12
{Toolchain}: mscc-toolchain-bin-2024.02.6-108
-- The C compiler identification is GNU 13.3.0
-- The CXX compiler identification is GNU 13.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/mscc/mscc-brsdk-arm64-2024.12/arm64-armv8_a-linux-gnu/xstax/release/x86_64-linux/bin/aarch64-linux-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/mscc/mscc-brsdk-arm64-2024.12/arm64-armv8_a-linux-gnu/xstax/release/x86_64-linux/bin/aarch64-linux-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Project name          = mepa_api
--   Type                = Release
--   c_flags             = -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g0 -Wall -Wno-unknown-pragmas -Wlogical-op -Wno-array-bounds -Wno-stringop-overflow -fasynchronous-unwind-tables -std=c11 -D_POSIX_C_SOURCE=200809L -D_BSD_SOURCE -D_DEFAULT_SOURCE -ldl -O3 -DNDEBUG
--   EXE_LINKER_FLAGS    =
--   shared_linker_flags =
-- Build mepa including
-- Looking for include file endian.h
-- Looking for include file endian.h - found
-- Looking for include file asm/byteorder.h
-- Looking for include file asm/byteorder.h - found
-- Excluding file: /home/administrator/GitHub/sw-mepa/mepa/microchip/lan80xx/src/lan80xx_serdes_config.h
-- Excluding file: /home/administrator/GitHub/sw-mepa/mepa/microchip/lan80xx/src/sha256/platform_util.h
-- Excluding file: /home/administrator/GitHub/sw-mepa/mepa/microchip/lan80xx/src/sha256/sha256.c
-- Excluding file: /home/administrator/GitHub/sw-mepa/mepa/microchip/lan80xx/src/sha256/sha256.h
-- Excluding file: /home/administrator/GitHub/sw-mepa/mepa/microchip/lan80xx/src/sha256/sha256_config.h
-- CMAKE_TOOLCHAIN_FILE='/opt/mscc/mscc-brsdk-arm64-2024.12/arm64-armv8_a-linux-gnu/xstax/release/x86_64-linux/share/buildroot/toolchainfile.cmake'
-- Configuring done (0.3s)
-- Generating done (0.1s)
-- Build files have been written to: /home/administrator/GitHub/sw-mepa/build-arm64
----

== Using a Custom BSP or Toolchain with MEPA

By default, MEPA will download the Microchip-released BSP and toolchain for the selected architecture. If you wish to use your own custom BSP or toolchain, you can do so by following these steps:

   * Place your extracted custom BSP or toolchain in the `/opt/mscc` directory.
   * Update the `build-artifact-version-string` argument in the relevant JSON files with name of your custom BSP or toolchain (`.cmake/deps-bsp.json` for BSP and `.cmake/deps-toolchain.json` for toolchain).
   * Run `create_cmake_project.rb` script

Following sections will provide a example to do so.  

=== Prepare Your Custom BSP or ToolchainCustom

 * BSP: Obtain or build your custom BSP tarball (e.g., `my-bsp.tar.gz`).
 * Custom Toolchain: Obtain or build your custom toolchain tarball (e.g., `my-toolchain.tar.gz`).

Extract them into `/opt/mscc`

----
sudo tar -xz -C /opt/mscc -f my-bsp.tar.gz
sudo tar -xz -C /opt/mscc -f my-toolchain.tar.gz
----

=== Update the JSON Configuration

Edit the following files to point to your custom BSP and/or toolchain:

 * .cmake/deps-bsp.json
 * .cmake/deps-toolchain.json

----
[
    {
        "id": "bsp",
        "type": "build-artifact",
        "build-artifact-url": "file:///opt/mscc",  // Use file:// for local path
        "build-artifact-version-string": "my-bsp"
    }
]

[
    {
        "id": "toolchain",
        "type": "build-artifact",
        "build-artifact-url": "file:///opt/mscc",
        "build-artifact-version-string": "my-toolchain"
    }
]
----

=== Run the CMake Project Creation Script

Now, run the script `./.cmake/create_cmake_project.rb <preset>` as usual.


== Selecting the Target and Building the SW

MEPA package supports cmake build infrastructure. Project configuration settings
may be specified interactively through the ccmake GUI.

The CMake project allows you to select what targets to build. By default, BUILD_mepa
(mepa common) is selected. Other targets should be selected as per requirement.

Sample run of LAN8814 library:

----
cd build-arm64
----

Run ccmake:

----
ccmake ..
----
Select MEPA_lan8814 target from ccmake GUI as below:

----
BUILD_mepa                       ON
CMAKE_BUILD_TYPE
CMAKE_INSTALL_PREFIX             /usr/local
MEPA_aqr                         OFF
MEPA_gpy211                      OFF
MEPA_ksz9031                     OFF
MEPA_lan8814                     ON
MEPA_vtss                        OFF
MEPA_vtss_opt_10g                OFF
MEPA_vtss_opt_1g                 OFF
MEPA_vtss_opt_cnt                64
MEPA_vtss_opt_macsec             OFF
MEPA_vtss_opt_ts                 OFF
MEPA_lan80xx_ts                  OFF
MEPA_lan80xx_ts_msec             OFF


MEPA_lan8814: Add LAN8814 support in libmeba
Press [enter] to edit option Press [d] to delete an entry CMake Version 3.16.3
Press [c] to configure
Press [h] for help Press [q] to quit without generating
Press [t] to toggle advanced mode (Currently Off)
----

Note:: To list of all targets available, use option 't' in the GUI:

After enabling the necessary targets Press [c] to configure the targets.
After configuration is complete Press [g] to generate Makefile with enabled targets.

Run make:

----
$ make
Scanning dependencies of target mepa_common
[ 0%] Building C object CMakeFiles/mepa_common.dir/common/src/phy.c.o
[ 33%] Linking C static library libmepa_common.a
[ 33%] Built target mepa_common
Scanning dependencies of target mepa_drv_lan8814
[ 66%] Building C object microchip/lan8814/CMakeFiles/mepa_drv_lan8814.dir/src/lan8814.c.o
[ 66%] Building C object microchip/lan8814/CMakeFiles/mepa_drv_lan8814.dir/src/lan8814_ts.c.o
[ 66%] Linking C static library libmepa_drv_lan8814.a
[ 66%] Built target mepa_drv_lan8814
Scanning dependencies of target mepa_target
[100%] Bundling mepa
[100%] Built target mepa_target
$
----

Once the build is done, the generated static libraries can be found as below:

----
$ find . -name "*.a"
./libmepa.a
./libmepa_common.a
./microchip/lan8814/libmepa_drv_lan8814.a
$
----
//TODO : What is final static library supposed to be used (all or one of above)
