// Copyright (c) 2004-2020 Microchip Technology Inc. and its subsidiaries.
// SPDX-License-Identifier: MIT

= MEPA-2025.12

== MEPA-2025.12
[cols="25%,75%"]
|===
|Version:          |MEPA-2025.12
|Previous Version: |MEPA-2025.09
|Date:             |2025-12-18
|Description:      |Release Notes
|===

=== Release Status

==== Bugs Fixed

  * *MEPA-1288*      : create_cmake_project script fails when used external to MCHP domain, reverted back to `/opt/mscc/` folder
  * *MEPA-1184*      : Firmware update fails in LAN80XX PHYs at higher management frequency
  * *MEPA-1257*      : 1000BASE-X Link shows up when LP advertise Clause-37 HDX whereas LAN80XX Advertise only FDX
  * *MEPA-1261*      : TS Classifier flow disable is not working in LAN80XX PTP Driver
  * *MEPA-1316*      : HI-BER Interrupt not triggered at 25G speed in LAN80XX PHY
  * *MEPA-1290*      : LTC LOAD is not working with continuous mode when it was set after SAVE in LAN80XX PHY
  * *MEPA-1317*      : LAN80XX PHY passthrough of undersized frames (less than 64 bytes) results in FCS error
  * *MEPA-1318*      : Incorrect register address for PTP ANA2 block in Register dump API of LAN80XX PHY
  * *MEPA-1109*      : Cross-connect Failover signal not routed to FAILOVER OUT PIN in LAN80XX
  * *MEPA-1296*      : Corrected incorrect return value for `lan80xx_phy_ts_pps_ouput_conf_set` API
  * *MEPA-1309*      : Seen packet drops when MACsec Tx AN Transition in VSC8258 got fixed
  * *MEPA-1313*      : MEPA IP Match Mode not converted to VTSS IP Match Mode when using VSC PHY's

==== Documentation update

  * *MEPA-1288*      : Getting started ADOC gets updated with instructions to run create_cmake_project script
  * *MEPA-1266*      : Updated MEPA ADOC with user guide for `mepa_synce_clock_conf_set()` API
  * *MEPA-1302*      : Updated MEPA ADOC with user guide for `mepa_ts_fifo_signature_set()`/`mepa_ts_fifo_signature_get()` APIs

==== New features and API enhancements

  * *MEPA-1254*      : Added support to dump PTP_LTC and PTP_STI registers for LAN80XX PHY 
  * *MEPA-1263*      : Added support to dump RS-FEC registers for LAN80XX PHY
  * *MEPA-1292*      : Added Dev pointer NULL check for all MEPA APIs
  * *MEPA-1294*      : Indy D0 PHY changes related to work-arounds in power configuration and UDP frame matching.
  * *MEPA-1245*      : Added MEPA support to retrieve IPv6 PTP Signature from PTP FIFO
  * *MEPA-1302*      : Introduced new MEPA API to configure PTP signature fields(`mepa_ts_fifo_signature_set()`/`mepa_ts_fifo_signature_get()`)
  * *MEPA-1297*      : Introduced new MEPA API in PTP Driver to read/write CSR Registers using address (`mepa_ts_csr_reg_read()`/`mepa_ts_csr_reg_write()`)
  * *MEPA-1266*      : Introduded MEPA wrapper function to configure SyncE in VSC8258 and LAN80XX PHYs (`mepa_synce_clock_conf_set()`) through MEPA API
  * *MEPA-1317*      : Modified API signature of `lan80xx_operating_mode_set()` to provide configurable support for LFS and MAC Padding

==== MEPA Sample Applications new features

  * *MEPA-1039*      : MACsec Key Rollover demo application with static key to encrypt and decrypt

==== Known issues:

  * *MEPA-644*       : SyncE Disable not working in VSC8258
  * *MEPA-793*       : When MACSec+1588 Enabled using VSC8584, after oos_mitigation there is very large PTP Offsets
  * *MEPA-1246*      : VSC8574 does not properly determine Link Status when Media is 100BaseFX Media
  * *MEPA-1084*      : LAN8814 w/long cable shows traffic FCS error and link down issue
  * *MEPA-966*       : Indy QSGMII serdes loopback broken
