// Copyright (c) 2004-2020 Microchip Technology Inc. and its subsidiaries.
// SPDX-License-Identifier: MIT

= SyncE Demo Application

== SyncE Demo Application Description
Synchronous Ethernet(SyncE) is an ITU-T standard which provides facilitates the transference of
clock signals over the Ethernet physical layer. Any network element (NE) should have at least two
reference clocks, and in addition, Ethernet interfaces must be able to generate their own
synchronization signal in case they lose their external reference.

SyncE Demo Application is used to configure the SyncE Block of PHYs for generating recovered clock A
and recovered clock B with the corresponding recovered clockout frequency achieved by utilizing
MEPA/Chip specfic APIs tailored for the respective PHY.

Following methods used for SyncE-Demo Application.

* Generic SyncE Demo for all the PHY's

* Chip Specific SyncE demo for specific PHY's

== Directory
* `./mepa_demo/mepa_apps/phy_synce.c` - Source File for Generic and chip specific SyncE Demo Application
* `./mepa_demo/mepa_scripts/synce_config.json` - JSON file for Chip specific Sync-E config, application will take configuration from this File

== Prerequisites
SyncE Demo Application to run on EDSx Platform User needs to flash `ext4` image on
eMMC flash, the application will not work with `.itb` image because it doesn't have the Linux File System.
To Configure the Chip specific SyncE we have a JSON file.

== Generic SyncE Demo Application

To Run SyncE Demo Application the 'mepa-demo-edsx' application needs to be running.
Reffer Section link:#mepa_demo/docs/getting-started[Getting-Started] to know about the procedure
to run 'mepa-demo' Application.

Once 'mepa-demo-edsx' application is started the Generic SyncE Demo Application can be configured with the command
'mepa-cmd synce_conf_set'.

=== Generic SyncE Demo Application Arguments

To List the all available arguments in the Generic SyncE Demo Application run the below mentioned command.


----
# mepa-cmd  synce_conf_set ?
Description:
------------
syncE configuration set for particular port number.

Syntax:
-------
synce_conf_set <port_no> [disableclk|serdes|coppermedia|clk1|clk2] [25mhz|31.25mhz|125mhz|156.25mhz] [clkouta|clkoutb]

Parameters:
-----------
<port_no>                              : Port number or zero
disableclk|serdes|coppermedia|clk1|clk2:
         DISABLECLK     : Disable clock source
         SERDES         : Serdes clock source
         COPPERMEDIA    : Coppermedia clock source
         CLK1           : Clock source1
         CLK2           : Clock source2

25mhz|31.25mhz|125mhz|156.25mhz        :
         25MHZ          : 25mhz expected clock frequency
         31.25MHZ       : 31.25mhz expected clock frequency
         125MHZ         : 125mhz expected clock frequency
         156.25MHZ      : 156.25mhz expected clock frequency

clkouta|clkoutb                        :
         CLKOUTA        : Recovered clock output A
         CLKOUTB        : Recovered clock output B
----

== Chip-Specific SyncE Demo Appplication

Configure all the options in the chip specific JSON file. Chip specific synce application will read the populated structure from JSON file
and configure the SyncE by calling API's.

=== Procedure to execute Chip specific Sync-E
----
#cd mepa-scripts
# mepa-cmd chip_specific_synce <port_no> -f synce_config.json
----

Note: For VSC8258 PHY, in the synce_config.json file when 'mode' option is configured with VTSS_CKOUT_SQUELCH_SRC_LINK_LINE0/1/2/3 or HOST0/1/2/3
squelch-inverse should be configured as '1'.

== Recovered clock frequency measurement

Once the above mentioned parameters got configured, generated recovered clock frequency from the syncE
can be measured using oscilloscope from RCKOUTA/B pins (Refer schematics for the respective PHY for probing pins).

== Known Issues

MEPA-643: Recovered clock1 not working in VIPER

MEPA-644: syncE disable not working in M10G
